port 26379
dir /tmp
sentinel resolve-hostnames yes
sentinel monitor secaudit-master redis-master 6379 2
sentinel down-after-milliseconds secaudit-master 5000
sentinel failover-timeout secaudit-master 60000
sentinel parallel-syncs secaudit-master 1
